Update gulp + gulp-sass & edit-config performance improvements
AceCentre/pasco pull request #274
Opened 2022-05-19 15:51 UTC by hosseinamin

In this PR I went ahead and updated the gulp module since it wasn't building on nodejs 17.

Issue #269 should be fixed with the performance improvements of this PR. edit-config page was having a hard time initializing the page. This is caused mainly by use of `rangeslider-js` module.

There are some minor bugfixes and typo fixes as well.

2022-05-20 08:52 UTC, gavinhenderson commented
> since it wasn't building on nodejs 17.

Can we target either node 16 or 18? 17 isn't an LTS (long term support) version so its best to avoid it.

2022-05-20 08:53 UTC, gavinhenderson requested changes

2022-05-20 08:53 UTC, gavinhenderson commented on html/js/edit-config.js
> +}
Can we make it clearer what these functions are doing, takes me a second to figure out that it is tearing down / initialising the slides. 

Can we change the function names to reflect what the function does, ie `destroy_all_sliders_on_page` and `initialise_all_sliders_on_page`?

Ideally it would be nice to have this in a `slider.js` file but probably makes sense to leave that until you are doing a full refactor

2022-05-20 08:53 UTC, gavinhenderson commented on html/js/edit-config.js
> +      );
Do we need to have an array of promises here that we wait for all to resolve?

Is there any benefit to using `.then()` over putting the `on_hide_page` directly in the callback? For example we could do this instead:

```js
new Promise(function (resolve) {
  $this.fadeOut(300, () => {
    on_hide_page();
    resolve();
  });
});
```

It would be nice if we could eventually ditch promises for async/await but thats probably a bigger task.

2022-05-20 08:53 UTC, gavinhenderson commented on html/jsx/uicommon.js
> +  if (elm[CONST.PLUGIN_NAME]) {
Could you add comment to the code explaining why we need to do this?

2022-05-20 08:53 UTC, gavinhenderson commented on html/js/edit-config.js
> +function set_needs_save_config () {
Can we add a comment about why we need this function?

2022-05-20 08:53 UTC, gavinhenderson commented on html/js/edit-config.js
> +  var hdlerr = typeof options.handle_errors == 'undefined' ? true : options.handle_errors
We can make this section a little cleaner with some new javascript features:

For example: 

```js
function do_save_config(options = {}) {
  const handleErrors = options.handle_errors ?? true;
```

Reference:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2022-05-20 08:59 UTC, hosseinamin commented on html/js/edit-config.js
> +}
Sure, We will go through this next, I'll be working on refactoring next. This PR is just for the bugfixes. So we can push it out asap.

2022-05-20 09:05 UTC, hosseinamin commented on html/js/edit-config.js
> +function set_needs_save_config () {
Well, This function is mainly called when there's a change in inputs. Throttling a call to save_config will reduce unnecessary attempts to save the config. Specially when the input is text, On every key stroke it will call set_needs_save_config.

2022-05-20 09:07 UTC, hosseinamin commented
> > since it wasn't building on nodejs 17.
> 
> Can we target either node 16 or 18? 17 isn't an LTS (long term support) version so its best to avoid it.

Node v17 was not my main concern. But it was the cause for the error. gulp-sass needed update.

2022-05-20 09:10 UTC, hosseinamin commented on html/jsx/uicommon.js
> +  if (elm[CONST.PLUGIN_NAME]) {
I'll change this function on next PRs.

2022-05-20 09:13 UTC, gavinhenderson commented on html/js/edit-config.js
> +function set_needs_save_config () {
Makes sense, can you add a comment in the code so when someone else comes across it in the future we can tell what it does.

2022-05-20 09:36 UTC, gavinhenderson commented
@hosseinamin After testing #269 still seems like an issue. It crashes at the same point.

Its worth noting it crashes when you come out of the settings page and the normal vocab/tree page loads. 

I can record a video if you need to see how to reproduce the error?

2022-05-21 10:47 UTC, hosseinamin commented
PR #268 has been added in this PR. And surprisingly the error message does not show up in this merge.

#269 bug is also fixed with the last few commits.

2022-05-23 10:14 UTC, merged